/**
 * Created by Administrator1 on 2017/2/27.
 */
requirejs.config({
    /*注意这里使用绝对路径*/
    baseUrl:"/",
    pasths:{
        //
        jquery:"lib/jquery/jquery.min",
        bootstrap:"lib/bootstrap/js/bootstrap.min"
    },
    shim:{
        bootstrap:{
            deps:["jquery"]
        }
    }
});
//所有的页面都需要这两个js，先加载它们
require(["jquery","bootstrap"]);
//这里获取页面的URL，然后加载对应的js模块
